blueprint:
  name: iPixel – Rotierende Mehrfachanzeige (Dauerlauf)
  description: >
    Zeigt mehrere Sensorwerte nacheinander auf einem iPixel Display an.
    Jeder Eintrag besitzt:
    - Eine Sensor-Entität (PV, SoC, Temperatur, …)
    - Ein Textformat (z. B. "PV {{ value }}W")
    - Unteren & oberen Wert zur Farbberechnung
    - Untere & obere RGB-Farbe (Color Selector)

    Zwischen low_color und high_color wird automatisch interpoliert.
    Das Display wechselt im einstellbaren Intervall (2–180 Sekunden).

    Der Whitespace-Trick verhindert sichtbare Farbwechsel,
    bevor der neue Text angezeigt wird.

  domain: automation

  input:
    display_entity:
      name: Display Text-Entity
      selector:
        entity:
          domain: text

    color_entity:
      name: Farb-Entity (Light)
      selector:
        entity:
          domain: light

    rotation_interval:
      name: Wechselintervall (Sekunden)
      default: 5
      selector:
        number:
          min: 2
          max: 180
          mode: slider
          unit_of_measurement: Sekunden

    entries:
      name: Anzuzeigende Einträge
      description: >
        Liste der rotierenden Anzeigen.
        Jede Anzeige benötigt:
        - entity: Sensor-Entität
        - text: Formatstring ("{{ value }}" wird ersetzt)
        - low_value: Unterer Farbbereich
        - high_value: Oberer Farbbereich
        - low_color: RGB unten (z. B. [255,0,0])
        - high_color: RGB oben (z. B. [0,255,0])

      default:
        - entity: sensor.meine_entitaet1
          text: "Entität 1: {{ value }}"
          low_value: 0
          high_value: 100
          low_color: [255, 0, 0]
          high_color: [0, 255, 0]

        - entity: sensor.meine_entitaet2
          text: "Entität 2: {{ value }}"
          low_value: 10
          high_value: 80
          low_color: [255, 0, 0]
          high_color: [0, 255, 0]

        - entity: sensor.meine_entitaet3
          text: "Entität 3: {{ value }}"
          low_value: 500
          high_value: 2500
          low_color: [255, 0, 0]
          high_color: [0, 255, 0]

      selector:
        object:

mode: restart

variables:
  display: !input display_entity
  color_light: !input color_entity
  entries: !input entries
  interval: !input rotation_interval
  total: "{{ entries | count }}"

action:
  - repeat:
      while: "{{ true }}"
      sequence:

        # ---------------------------------------------------------
        # 1) Index berechnen
        # ---------------------------------------------------------
        - variables:
            index: >
              {% set last = this.attributes.get('last_index', -1) | int %}
              {{ (last + 1) % total }}

            current: "{{ entries[index] }}"

            sensor_value: "{{ states(current.entity) | float(0) }}"

            ratio: >
              {% if sensor_value <= current.low_value %}
                0
              {% elif sensor_value >= current.high_value %}
                1
              {% else %}
                {{ (sensor_value - current.low_value) / (current.high_value - current.low_value) }}
              {% endif %}

            r: >
              {{ (current.low_color[0] + (current.high_color[0] - current.low_color[0]) * ratio) | int }}
            g: >
              {{ (current.low_color[1] + (current.high_color[1] - current.low_color[1]) * ratio) | int }}
            b: >
              {{ (current.low_color[2] + (current.high_color[2] - current.low_color[2]) * ratio) | int }}

            formatted_text: >
              {{ current.text | replace("{{ value }}", sensor_value | round(0) | string ) }}

        # Index speichern
        - service: automation.modify
          data:
            entity_id: "{{ this.entity_id }}"
            variables:
              last_index: "{{ index }}"

        # ---------------------------------------------------------
        # 2) Whitespace → Farbe → Text
        # ---------------------------------------------------------

        - service: text.set_value
          target:
            entity_id: "{{ display }}"
          data:
            value: " "

        - service: light.turn_on
          target:
            entity_id: "{{ color_light }}"
          data:
            rgb_color: ["{{ r }}", "{{ g }}", "{{ b }}"]

        - service: text.set_value
          target:
            entity_id: "{{ display }}"
          data:
            value: "{{ formatted_text }}"

        # ---------------------------------------------------------
        # 3) Warten bis nächster Eintrag
        # ---------------------------------------------------------
        - delay:
            seconds: "{{ interval }}"
