blueprint:
  name: "Benachrichtigung bei nicht verfügbaren Entitäten oder Geräten"
  description: >
    Sendet eine Benachrichtigung, wenn ausgewählte Entitäten oder Geräte für eine bestimmte Zeit nicht verfügbar sind.
    Du kannst wählen, ob bei jedem einzelnen Element oder nur wenn alle zusammen nicht verfügbar sind, benachrichtigt wird.
  domain: automation
  input:
    monitored_entities:
      name: "Zu überwachende Entitäten"
      description: "Wähle die Entitäten aus, die überwacht werden sollen. (Optional)"
      default: []
      selector:
        entity:
          multiple: true
    monitored_devices:
      name: "Zu überwachende Geräte"
      description: "Wähle die Geräte aus, die überwacht werden sollen. (Optional)"
      default: []
      selector:
        device:
          multiple: true
    unavailable_time:
      name: "Zeit in Sekunden"
      description: "Wie lange die Elemente nicht verfügbar sein müssen, bevor die Benachrichtigung ausgelöst wird."
      default: 10
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
          mode: slider
    use_friendly_name:
      name: "Friendly Name verwenden"
      description: "Wenn aktiviert, wird der Friendly Name des Elements in der Benachrichtigung verwendet."
      default: false
      selector:
        boolean: {}
    notify_service:
      name: "Benachrichtigungsdienst"
      description: "Wähle den Benachrichtigungsdienst aus, um die Nachricht zu senden."
      selector:
        select:
          options:
            - notify.mobile_app_<your_device_name>
            - notify.pushover
            - notify.telegram
          custom_value: true
    notify_mode:
      name: "Benachrichtigungsmodus"
      description: "Wähle, ob bei jedem einzelnen Element oder nur wenn alle zusammen nicht verfügbar sind, benachrichtigt werden soll."
      default: "individual"
      selector:
        select:
          options:
            - label: "Einzeln"
              value: "individual"
            - label: "Alle zusammen"
              value: "all"
    max_notifications:
      name: "Maximale Anzahl der Benachrichtigungen"
      description: "Die maximale Anzahl der zu sendenden Benachrichtigungen."
      default: 10
      selector:
        number:
          min: 1
          max: 100
          mode: slider
    custom_message:
      name: "Benutzerdefinierte Nachricht für 'Alle zusammen'"
      description: "Gib hier deine benutzerdefinierte Nachricht ein, die gesendet wird, wenn alle Elemente nicht verfügbar sind."
      default: "Alle überwachten Elemente sind nicht verfügbar!"
      selector:
        text:
          multiline: true
    critical_notification:
      name: "Kritische Benachrichtigung"
      description: "Wenn aktiviert, wird die Benachrichtigung als kritisch gesendet."
      default: false
      selector:
        boolean: {}

variables:
  monitored_entities: !input monitored_entities
  monitored_devices: !input monitored_devices
  use_friendly_name: !input use_friendly_name
  unavailable_time: !input unavailable_time
  notify_mode: !input notify_mode
  custom_message: !input custom_message
  critical_notification: !input critical_notification
  all_entities: >
    {{ monitored_entities | list + 
       (expand(monitored_devices) | map(attribute='entity_id') | list) }}

trigger:
  - platform: state
    entity_id: "{{ all_entities }}"
    to: "unavailable"
    for:
      seconds: !input unavailable_time

condition:
  - condition: template
    value_template: "{{ all_entities | length > 0 }}"
  - condition: template
    value_template: >
      {% if notify_mode == 'all' %}
        {% set unavailable_count = 0 %}
        {% for entity in all_entities %}
          {% if states(entity) == 'unavailable' %}
            {% set unavailable_count = unavailable_count + 1 %}
          {% endif %}
        {% endfor %}
        {{ unavailable_count == all_entities | length }}
      {% else %}
        true
      {% endif %}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ notify_mode == 'individual' }}"
        sequence:
          - variables:
              entity_id: "{{ trigger.entity_id }}"
              friendly_name: "{{ state_attr(trigger.entity_id, 'friendly_name') }}"
          - service: !input notify_service
            data:
              title: "Element nicht verfügbar"
              message: >
                {% if use_friendly_name and friendly_name is not none %}
                  Das Element "{{ friendly_name }}" ist seit mehr als {{ unavailable_time }} Sekunden nicht verfügbar.
                {% else %}
                  Das Element "{{ entity_id }}" ist seit mehr als {{ unavailable_time }} Sekunden nicht verfügbar.
                {% endif %}
              data:
                push:
                  category: "{{ 'critical' if critical_notification else '' }}"
    default:
      - service: !input notify_service
        data:
          title: "Alle überwachten Elemente nicht verfügbar"
          message: "{{ custom_message }}"
          data:
            push:
              category: "{{ 'critical' if critical_notification else '' }}"

mode: parallel
max: !input max_notifications
