blueprint:
  name: Luftfeuchtigkeit Status & Differenz
  description: Erstellt zwei Template-Sensoren für Lüftungsstatus und Feuchtigkeitsdifferenz eines Raumes.
  domain: template
  input:
    sensor_raum:
      name: Sensor Raum
      description: Entität für absolute Luftfeuchtigkeit im Raum (z.B. sensor.thermal_comfort_bad_eg_absolute_luftfeuchtigkeit)
      selector:
        entity:
          domain: sensor
    sensor_aussen:
      name: Sensor Außen
      description: Entität für absolute Luftfeuchtigkeit außen (z.B. sensor.thermal_comfort_garten_absolute_luftfeuchtigkeit)
      selector:
        entity:
          domain: sensor
    status_name:
      name: Name Status Sensor
      description: Anzeigename für den Status-Sensor (z.B. "Bad EG Status lüften")
      selector:
        text:
    status_unique_id:
      name: Unique ID Status Sensor
      description: Eindeutige ID für den Status-Sensor (z.B. "bad_eg_status_luften")
      selector:
        text:
    diff_name:
      name: Name Differenz Sensor
      description: Anzeigename für den Differenz-Sensor (z.B. "Bad EG Luftfeuchtigkeit Differenz")
      selector:
        text:
    diff_unique_id:
      name: Unique ID Differenz Sensor
      description: Eindeutige ID für den Differenz-Sensor (z.B. "bad_eg_luftfeuchtigkeit_differenz")
      selector:
        text:

template:
  - sensor:
      - name: !input status_name
        unique_id: !input status_unique_id
        state: >
          {% set diff = states('!input sensor_raum')|float(0) - states('!input sensor_aussen')|float(0) %}
          {% if diff > 0.5 %}
            OK
          {% else %}
            NICHT OK
          {% endif %}
      - name: !input diff_name
        unique_id: !input diff_unique_id
        state: >
          {{ states('!input sensor_raum')|float(0) - states('!input sensor_aussen')|float(0) }}
